apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: pg-admin
  namespace: pg-admin
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
